{"name": "test_login_1_error_4", "status": "passed", "description": "登录失败", "attachments": [{"name": "log", "source": "3ad0dabf-f84e-4dc7-bfe3-bfe130fb277d-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "7741657f-a3ba-434f-9135-1dd4d420ade1-attachment.txt", "type": "text/plain"}], "start": 1617349195362, "stop": 1617349196082, "uuid": "727a3e80-38ad-4769-acb8-17b03fd4b637", "historyId": "c8d39efab6e43a30efd145fedadb7d50", "testCaseId": "bfcd46d0b691661fbda65475e1108c98", "fullName": "tests.test_a1_login.TestLogin#test_login_1_error_4", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_a1_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-U13POE8"}, {"name": "thread", "value": "6480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_a1_login"}]}