{"name": "test_capital_1_error_3", "status": "passed", "description": "新增资金账户失败的用例", "attachments": [{"name": "log", "source": "39fc1c06-047e-479e-90dc-716fe5c657de-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "6a20c400-73ee-4beb-8558-03f5e1d6a292-attachment.txt", "type": "text/plain"}], "start": 1617349295433, "stop": 1617349296715, "uuid": "bcdb5afe-063f-4553-8542-1e27a9b04ec0", "historyId": "84f771e746b8b37bc0f5696f9e432399", "testCaseId": "6c7719e7d17f89ef9e0feb8230f89998", "fullName": "tests.test_a5_addfundaccount.TestNewlyCompany#test_capital_1_error_3", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_a5_addfundaccount"}, {"name": "subSuite", "value": "TestNewlyCompany"}, {"name": "host", "value": "DESKTOP-U13POE8"}, {"name": "thread", "value": "6480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_a5_addfundaccount"}]}