{"name": "test_control_account_a1_error_8", "status": "passed", "description": "添加风控账户失败得用例", "attachments": [{"name": "log", "source": "299b5ace-e138-4a35-8d03-5cc08422fbba-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "91f4b952-a4a5-408b-964e-f03af5b6cc8f-attachment.txt", "type": "text/plain"}], "start": 1617349272086, "stop": 1617349273320, "uuid": "dc3f43a7-8de8-4613-a1bd-298706362578", "historyId": "c679d950c291f2da1db5e7c01f72313f", "testCaseId": "79c29adaf1b10acdc5843e8a98550639", "fullName": "tests.test_a4_Riskcontrolaccount.TestAddRiskControlAccount#test_control_account_a1_error_8", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_a4_Riskcontrolaccount"}, {"name": "subSuite", "value": "TestAddRiskControlAccount"}, {"name": "host", "value": "DESKTOP-U13POE8"}, {"name": "thread", "value": "6480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_a4_Riskcontrolaccount"}]}