{"name": "test_capital_1_error_2", "status": "passed", "description": "新增资金账户失败的用例", "attachments": [{"name": "log", "source": "ec8efdad-f694-428b-bb56-6e20c0f72b34-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "e0378703-1ba1-4045-a506-500299224135-attachment.txt", "type": "text/plain"}], "start": 1617349294139, "stop": 1617349295430, "uuid": "f857da0f-70b8-4b6b-9cff-9c311b62d670", "historyId": "0a621cc45f3180ae65cb395882bb9ac7", "testCaseId": "47fe779215e3e293a7b5eed2e8215a7d", "fullName": "tests.test_a5_addfundaccount.TestNewlyCompany#test_capital_1_error_2", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_a5_addfundaccount"}, {"name": "subSuite", "value": "TestNewlyCompany"}, {"name": "host", "value": "DESKTOP-U13POE8"}, {"name": "thread", "value": "6480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_a5_addfundaccount"}]}