{"name": "test_login_1_error_3", "status": "passed", "description": "登录失败", "attachments": [{"name": "log", "source": "a1485e66-ef96-4eeb-b9db-5c10ce3ae514-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "946e2c52-f53e-4ea6-b438-69c23f49fe60-attachment.txt", "type": "text/plain"}], "start": 1617349194569, "stop": 1617349195360, "uuid": "689c9a3d-7eb0-4e72-a5cb-3fdd2f7c310a", "historyId": "fc923ee6c0aa633e6baefc6d46d0e889", "testCaseId": "080a2cbfb677ffd455e863c065f66bd4", "fullName": "tests.test_a1_login.TestLogin#test_login_1_error_3", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_a1_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-U13POE8"}, {"name": "thread", "value": "6480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_a1_login"}]}