{"name": "test_capital_1_error_4", "status": "passed", "description": "新增资金账户失败的用例", "attachments": [{"name": "log", "source": "2b2434e2-2465-49c0-9a1b-d892bf05de54-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "4ba6f99d-749e-4668-a60c-47164b042879-attachment.txt", "type": "text/plain"}], "start": 1617349296717, "stop": 1617349298049, "uuid": "94e8344e-126e-4c8a-b79b-11d25cb132e3", "historyId": "36cb35b53a97d4a75c3ab92e1bb4d0d6", "testCaseId": "cfc852083eee772983e20eaeee13e436", "fullName": "tests.test_a5_addfundaccount.TestNewlyCompany#test_capital_1_error_4", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_a5_addfundaccount"}, {"name": "subSuite", "value": "TestNewlyCompany"}, {"name": "host", "value": "DESKTOP-U13POE8"}, {"name": "thread", "value": "6480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_a5_addfundaccount"}]}